## R installation

In [ ]:
!pip install -q rpy2
%load_ext rpy2.ipython

## Addition with Data Vectors

In [ ]:
%%R
c(2,3,5,7)+c(-2,-3,5,8)

[1]  0  0 10 15


In [ ]:
%%R
c(2,3,5,7)+c(-2,3)

[1]  0  6  3 10


## Subtraction with Data Vectors

In [ ]:
%%R
c(2,3,5,7)-c(-2,-3,5,8)

[1]  4  6  0 -1


In [ ]:
%%R
c(2,3,5,7)-c(-2,3)

[1] 4 0 7 4


## Multiplication with Data Vectors

In [ ]:
%%R
c(2,3,5,7)*c(9,7,5,8)

[1] 18 21 25 56


In [ ]:
%%R
c(2,3,5,7)*c(2,3)

[1]  4  9 10 21


## Division with Data Vectors

In [ ]:
%%R
c(15,16,18,20,22)/c(3,4,6,10,11)

[1] 5 4 3 2 2


In [ ]:
%%R
c(60,80,20,40)/c(2,4)

[1] 30 20 10 10


## Assignment operator

In [ ]:
%%R
x <- 20
print(x)
y = x * 2
print(y)
z=x+y
print(z)

[1] 20
[1] 40
[1] 60


In [ ]:
%%R
m1 = "apple"
print(m1)
m2 <- 'apple'
print(m2)
m3 = 'apple'
print(m3)
m4 <- "apple1"
print(m4)

[1] "apple"
[1] "apple"
[1] "apple"
[1] "apple1"


## Knowing numbers and characters

In [ ]:
%%R
x=20

print(is.numeric(x))

print(is.character(x))

[1] TRUE
[1] FALSE


In [ ]:
%%R
m="apple"

print(is.numeric(m))

print(is.character(m))

[1] FALSE
[1] TRUE


## Converting numbers and characters

In [ ]:
%%R
x = 20
print(is.numeric(x))

y = as.character(x)
print(is.numeric(y))

print(is.character(y))

print(y)

[1] TRUE
[1] FALSE
[1] TRUE
[1] "20"


In [ ]:
%%R
y = "apple"
print(is.numeric(y))
print(is.character(y))

z = suppressWarnings(as.numeric(y))
print(is.numeric(z))

print(is.character(z))

print(z)

[1] FALSE
[1] TRUE
[1] TRUE
[1] FALSE
[1] NA


## Combining values in a data vector

In [ ]:
%%R
y=c(1,5,3,2,4)
print(y)

[1] 1 5 3 2 4


## Mode

In [ ]:
%%R
x=6
print(mode(x))

y="apple"
print(mode(y))

[1] "numeric"
[1] "character"


## Infinity

In [ ]:
%%R
print(3/0)

print(5+Inf)

x = 5+Inf
print(is.finite(x))

print(is.infinite(x))

[1] Inf
[1] Inf
[1] FALSE
[1] TRUE


## R as a calculator

In [ ]:
%%R
print((2+3)*5 + 5 - 10)

[1] 20


In [ ]:
%%R
print(2+5)

print(2 + 5)

print(2     +     5)

print(2       +5)

[1] 7
[1] 7
[1] 7
[1] 7


## Addition with scalar

In [ ]:
%%R
c(2,3,5,7) + 10

[1] 12 13 15 17


## Subtraction with scalar

In [ ]:
%%R
c(2,3,5,7) - 10

[1] -8 -7 -5 -3


## Multiplication with scalar

In [ ]:
%%R
c(2,3,5,7) * 10

[1] 20 30 50 70


## Division with scalar

In [ ]:
%%R
c(2,3,5,7) / 10

[1] 0.2 0.3 0.5 0.7


## R as a calculator

In [ ]:
%%R
print(2^3)

print(2**3)

[1] 8
[1] 8


In [ ]:
%%R
print(2^0.5)

print(2**0.5)

print(2^-0.5)

[1] 1.414214
[1] 1.414214
[1] 0.7071068


## Power operator with scalar

In [ ]:
%%R
print(c(2,3,6,5,4,7)^2)

print(c(2,3,5,7)^c(2,3))

print(c(1,2,3,4,5,6)^c(2,3,4))

[1]  4  9 36 25 16 49
[1]   4  27  25 343
[1]    1    8   81   16  125 1296


## Integer division with scalar

In [ ]:
%%R
print(4 %/% 4)

print(5 %/% 2)

print(7 %/% 3)

[1] 1
[1] 2
[1] 2


## Integer division with scalar

In [ ]:
%%R
c(2,3,5,7) %/% 2

[1] 1 1 2 3


## Integer division with data vector

In [ ]:
%%R
c(2,3,5,7) %/% c(2,3)

[1] 1 1 2 2


## Modulo Division (x mod y) with scalars

In [ ]:
%%R
print(2 %% 2)

print(5 %% 2)

print(7 %% 3)

print(19 %% 5)

[1] 0
[1] 1
[1] 1
[1] 4


## Modulo Division (x mod y) with scalars

In [ ]:
%%R
c(2,3,5,7) %% 2

[1] 0 1 1 1


## Modulo Division (x mod y) with data vectors

In [ ]:
%%R
c(2,3,5,7) %% c(2,3)

[1] 0 0 1 1


## R as a calculator

In [ ]:
%%R
print(max(1.2, 3.4, -7.8))

print(min(1.2, 3.4, -7.8))

print(mean(2, 3, 4))

print(mean(c(2, 3, 4)))

print(abs(-4))

print(abs(c(-1,-2,-3,4,5)))

print(sqrt(4))

print(sqrt(c(2,3,4,5)))

print(log(2))

print(log(c(2,3,4,5)))

print(log10(100))

print(log10(c(2,3,4,5)))

[1] 3.4
[1] -7.8
[1] 2
[1] 3
[1] 4
[1] 1 2 3 4 5
[1] 2
[1] 1.414214 1.732051 2.000000 2.236068
[1] 0.6931472
[1] 0.6931472 1.0986123 1.3862944 1.6094379
[1] 2
[1] 0.3010300 0.4771213 0.6020600 0.6989700


## Assignments

In [ ]:
%%R
x1 = c(1,2,3,4)
print(x1)

x2 = x1^2
print(x2)

[1] 1 2 3 4
[1]  1  4  9 16


In [ ]:
%%R
c(1,2,3,4) + sum(c(1,2,3,4)) * prod(c(1,2))

[1] 21 22 23 24


In [ ]:
%%R
abs( c(1,2,3,4) - sum(c(1,2,3,4))*prod(c(1,2)) )

[1] 19 18 17 16


## Matrix

In [ ]:
%%R
x = matrix( nrow=4, ncol=2,data=c(1,2,3,4,5,6,7,8) )

print(x)

print(x[3,2])

     [,1] [,2]
[1,]    1    5
[2,]    2    6
[3,]    3    7
[4,]    4    8
[1] 7


## Entering data column wise in a matrix

In [ ]:
%%R
x = matrix( nrow=4, ncol=2,data=c(1,2,3,4,5,6,7,8))
print(x)

     [,1] [,2]
[1,]    1    5
[2,]    2    6
[3,]    3    7
[4,]    4    8


In [ ]:
%%R
x = matrix( nrow=4, ncol=2,data=c(1,2,3,4,5,6,7,8), byrow = FALSE)
print(x)

     [,1] [,2]
[1,]    1    5
[2,]    2    6
[3,]    3    7
[4,]    4    8


## Entering data row wise in a matrix

In [ ]:
%%R
y = matrix( nrow=4, ncol=2,data=c(1,2,3,4,5,6,7,8), byrow = TRUE)

print(y)

     [,1] [,2]
[1,]    1    2
[2,]    3    4
[3,]    5    6
[4,]    7    8


## Properties of a Matrix

In [ ]:
%%R
print(dim(x))

print(ncol(x))

print(nrow(x))

print(mode(x))

print(attributes(x))

[1] 4 2
[1] 2
[1] 4
[1] "numeric"
$dim
[1] 4 2



## Help on the Object "Matrix"

In [ ]:
%%R
help("matrix")

File: /tmp/RtmpiszFjm/Rtxt4f8529d7ac0
matrix                  package:base                   R Documentation



_M_a_t_r_i_c_e_s



_D_e_s_c_r_i_p_t_i_o_n:



     ‘matrix’ creates a matrix from the given set of values.



     ‘as.matrix’ attempts to turn its argument into a matrix.



     ‘is.matrix’ tests if its argument is a (strict) matrix.



_U_s_a_g_e:



     matrix(data = NA, nrow = 1, ncol = 1, byrow = FALSE,

            dimnames = NULL)

     

     as.matrix(x, ...)

     ## S3 method for class 'data.frame'

     as.matrix(x, rownames.force = NA, ...)

     

     is.matrix(x)

     

_A_r_g_u_m_e_n_t_s:



    data: an optional data vector (including a list or ‘expression’

          vector).  Non-atomic classed R objects are coerced by

          ‘as.vector’ and all attributes discarded.



    nrow: the desired number of rows.



    ncol: the desired number of columns.



   byrow: logical. If ‘FALSE’ (the default) the matrix is fille